# Generated by Django 5.1.3 on 2024-11-25 10:52

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djathtasApp', '0004_remove_video_url_remove_video_url_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
