# Generated by Django 5.1.3 on 2024-11-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djathtasApp', '0005_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anetarsimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emer', models.CharField(max_length=100)),
                ('mbiemer', models.CharField(max_length=100)),
                ('atesi', models.CharField(max_length=100)),
                ('mamesi', models.CharField(max_length=100)),
                ('vendlindja', models.CharField(max_length=100)),
                ('datelindja', models.DateField()),
                ('nid', models.CharField(max_length=20, unique=True)),
                ('gjinia', models.CharField(choices=[('male', 'Mashkull'), ('female', 'Femër')], max_length=10)),
                ('arsimi', models.CharField(max_length=200)),
                ('punesimi', models.CharField(max_length=200)),
                ('numer_telefoni', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('x', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('qarku', models.CharField(max_length=100)),
                ('bashkia', models.CharField(max_length=100)),
                ('emer_mbiemer', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
