# Generated by Django 5.1.3 on 2024-11-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djathtasApp', '0006_anetarsimi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anetarsimi',
            name='facebook',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='anetarsimi',
            name='instagram',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='anetarsimi',
            name='x',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='anetarsimi',
            name='youtube',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
