# Generated by Django 5.1.3 on 2024-12-05 12:27

import django.db.models.deletion
import django_ckeditor_5.fields
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djathtasApp', '0007_alter_anetarsimi_facebook_alter_anetarsimi_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtikujInfomues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artikujt_images/')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='anetarsimi',
            name='gjinia',
            field=models.CharField(choices=[('male', 'Mashkull'), ('female', 'Femër'), ('other', 'Tjeter')], max_length=10),
        ),
        migrations.CreateModel(
            name='ArtikujtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artikujt_images/')),
                ('artikuj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='djathtasApp.artikujinfomues')),
            ],
        ),
        migrations.CreateModel(
            name='ArtikujtVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('artikuj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='djathtasApp.artikujinfomues')),
            ],
        ),
    ]
