# Generated by Django 5.1.3 on 2024-12-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djathtasApp', '0009_rename_artikujtimage_artikujimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikujinfomues',
            name='video',
        ),
        migrations.AlterField(
            model_name='artikujinfomues',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
