# Generated by Django 5.1.3 on 2024-12-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djathtasApp', '0010_remove_artikujinfomues_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikujinfomues',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
