# Generated by Django 5.1.3 on 2024-12-12 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djathtasApp', '0012_prova'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prova',
        ),
        migrations.AlterModelOptions(
            name='artikujinfomues',
            options={'ordering': ['-published_at']},
        ),
        migrations.AddField(
            model_name='artikujinfomues',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
