# Generated by Django 5.1.3 on 2025-01-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djathtasApp', '0014_urlvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlvisit',
            name='url',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
